# Generated by Django 5.2.4 on 2025-07-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("change", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangeoffer",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Ожидает"),
                    ("accepted", "Принято"),
                    ("declined", "Отклонено"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Статус предложения",
            ),
        ),
    ]
