# Generated by Django 5.2.4 on 2025-07-17 13:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_alter_product_user"),
        ("change", "0003_alter_exchangeoffer_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="Ad",
        ),
    ]
